# Site settings
title: m
header-img: img/home-bg.png
email: meryltestflatiron@gmail.com
copyright_name: meryltestflatiron
description: > # this means to ignore newlines until "baseurl:"
  m
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  meryltestflatiron
learn_profile: meryltestflatiron
email_username: meryltestflatiron@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
